                                        <div class="modal fade" id="mdlPP" data-bs-keyboard="false" tabindex="-1" aria-labelledby="mdlPPTitle" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title h5" id="mdlPPTitle" style="color:#ddd;">Privacy Policy</h5>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                    </div>
                                                    <div class="modal-body" style="text-align:center; color:#ddd;">
                                                     
<b>Your Personal Information</b>
<br><br>
We only collect the information required to create your membership and complete your bookings. We only transmit the information to third parties when it is necessary to complete a transaction you have made, and even then, we only transmit the information necessary to complete the transaction. We will never rent or sell your information to any non-affiliated third party.
<br><br>
<b>Security, Storage and Use of Your Information</b>
<br><br>
Like most other websites, ours employs encrypted strings of text that we store on your computer, called cookies, if your settings allow for this. We do require the use of cookies while you are using our websites, as without them, we would not be able to provide a consistent user experience from page to page. One example is that unless we use cookies we would have no way to recall the arrival and departure dates used when you were booking a hotel or resort, and therefore, we could not verify if a hotel or resort were available to be booked.
<br><br>
Even so, we never use cookies to gather any information that is not directly related to your use of our website. For example, we do not track your use of any website except for ours, and for the reasons mentioned above. Cookies are not known to damage your computer or otherwise corrupt or damage programs or files. We cannot guarantee a positive experience on our website if you disable cookies, and this may adversely affect our ability to complete any transactions you attempt to make. Many browsers provide an option allow cookies from certain websites, and not from others. Consult your browser help section to access these features.
<br><br>
<b>Services Provided by Third Parties</b>
<br><br>
We do contract with certain third-party processors to process credit cards and other payment options for the transactions you complete. We never store your payment data in our systems, instead, you must enter that data each time you make a transaction. Payment processors we use have state-of-the-art, PCI compliant platforms, and are also prohibited from sharing, renting or selling your data.
<br><br>
Your personal information may be transmitted for the following reasons:
<br><br>
<ul>
<li>Processing credit/debit cards to complete your transactions</li>
<li>To help resolve billing or transactional disputes</li>
<li>To discover and deter fraud, and/or breaches of security or illegal acts</li>
</ul>
<br><br>
TravSavers partners with Stripe in order to facilitate payment for certain services and goods as found on TravSavers. TravSavers may disclose your personal information to Stripe for the following purposes:
<br><br>
Please be aware that a portion of the site's content has been generated by an AI system and may contain errors, inconsistencies, or outdated information. It is provided as-is without any warranties or guarantees of accuracy. We strongly recommend using this content as a starting point for further research. We disclaim any liability for damages or losses resulting from the use or reliance on this content.
<br><br>
Additionally, you may view Westgate Resorts' privacy policy <a href="( www.westgateresorts.com/privacy-policy/">here</a>  


                                                    </div>
                                                </div>
                                            </div>
                                        </div>

<!-- TERMS -->

                                        <div class="modal fade" id="mdlTerms" data-bs-keyboard="false" tabindex="-1" aria-labelledby="mdlTermsTitle" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title h5" id="mdlTermsTitle" style="color:#ddd;">Terms & Conditions</h5>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                    </div>
                                                    <div class="modal-body" style="color:#ddd;">
                                                     
To accept this promotional offer you must meet promotional qualifications and agree to the following terms & conditions.
<br><br>
Guest is responsible for the on-site payment of any additional resort fees the property may charge, resort fees may change without notice, please confirm with property. Reservations are made on a space available basis.  Inventory on the site is updated daily, but may not reflect real-time availability. Price offers are made for a limited time due to price fluctuation, expire soon after they are posted, and are subject to change.  Your card will be authorized upon booking and final payment will not be processed until the reservation is fully confirmed, usually within 24-72 hours.  Authorizations for reservations that cannot be confirmed will be released without charge.
<br><br>
<b><u>Promotional Qualifications</u></b><br><br>
<ul>
<li>As part of this promotion, your attendance at a 120-minute no-obligation sales presentation is required</li>
<li>Guests must be at least 28 years of age & have a combined household income of $60,000 (Single females must be 30 years of age, have $100,000 income, and be a major CC holder.  No single males.)</li>
<li>If married, cohabitating, or in a life partnership, both parties must attend together and show proof of co-residence by presenting matching ID/documents</li>
<li>Guests must present a major credit card (debit cards not accepted), and both parties must speak and understand fluent English</li>
<li>Your reservation request will not be finalized until we can confirm your reservation details with you via phone</li>
</ul>
<br>
Intentional misrepresentation of these qualifications may result in the cancellation of this package and forfeiture of the package price paid.
<br><br>
This offer is not valid for:<br><br>

<li>Guests who live within 60 miles of the property
<li>Westgate employees, Westgate timeshare owners, Westgate VOA owners, individuals employed in the vacation ownership industry, or realtors
<li>Guests who have scheduled for any other tour with Westgate during their stay.
<li>Persons who have received the vacation package as a gift from a second party.
<li>Anyone who is in the process of bankruptcy or foreclosure.
<li>Group travel (three or more couples or singles traveling together on separate packages).
<li>Anyone attending / participating in a sporting event, convention, or family reunion.
<li>Children or parents of Westgate owners.
<li>If a customer has previously toured Westgate Travel Club, they are not eligible to tour Westgate Resorts again.
<li>Persons who are consuming alcohol or under the influence of alcohol at the time of the promotional presentation.
<li>Persons who have toured Westgate twice in a lifetime. A qualified customer must wait a full twelve
(12) months before touring the same destination they have previously toured and 6 months to tour a
different destination during value and standard season.
<br><br>
Offer Sponsored by Westgate Resorts. Offer void where prohibited by law. This offer is made in compliance with the law of jurisdiction in which the projects are located. 
<br><br>
THIS ADVERTISING MATERIAL IS BEING USED FOR THE PURPOSE OF SOLICITING SALES OF TIMESHARE INTERESTS OR PLANS



                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                     
                                     