                                        <div class="modal fade" id="mdlPP" data-bs-keyboard="false" tabindex="-1" aria-labelledby="mdlPPTitle" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title h5" id="mdlPPTitle" style="color:#ddd;">Privacy Policy</h5>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                    </div>
                                                    <div class="modal-body" style="text-align:center; color:#ddd;">
                                                     
<b>Your Personal Information</b>
<br><br>
We only collect the information required to create your membership and complete your bookings. We only transmit the information to third parties when it is necessary to complete a transaction you have made, and even then, we only transmit the information necessary to complete the transaction. We will never rent or sell your information to any non-affiliated third party.
<br><br>
<b>Security, Storage and Use of Your Information</b>
<br><br>
Like most other websites, ours employs encrypted strings of text that we store on your computer, called cookies, if your settings allow for this. We do require the use of cookies while you are using our websites, as without them, we would not be able to provide a consistent user experience from page to page. One example is that unless we use cookies we would have no way to recall the arrival and departure dates used when you were booking a hotel or resort, and therefore, we could not verify if a hotel or resort were available to be booked.
<br><br>
Even so, we never use cookies to gather any information that is not directly related to your use of our website. For example, we do not track your use of any website except for ours, and for the reasons mentioned above. Cookies are not known to damage your computer or otherwise corrupt or damage programs or files. We cannot guarantee a positive experience on our website if you disable cookies, and this may adversely affect our ability to complete any transactions you attempt to make. Many browsers provide an option allow cookies from certain websites, and not from others. Consult your browser help section to access these features.
<br><br>
<b>Services Provided by Third Parties</b>
<br><br>
We do contract with certain third-party processors to process credit cards and other payment options for the transactions you complete. We never store your payment data in our systems, instead, you must enter that data each time you make a transaction. Payment processors we use have state-of-the-art, PCI compliant platforms, and are also prohibited from sharing, renting or selling your data.
<br><br>
Your personal information may be transmitted for the following reasons:
<br><br>
<ul>
<li>Processing credit/debit cards to complete your transactions</li>
<li>To help resolve billing or transactional disputes</li>
<li>To discover and deter fraud, and/or breaches of security or illegal acts</li>
</ul>
<br><br>
TravNow partners with Stripe in order to facilitate payment for certain services and goods as found on TravNow. TravNow may disclose your personal information to Stripe for the following purposes:
<br><br>
Please be aware that a portion of the site's content has been generated by an AI system and may contain errors, inconsistencies, or outdated information. It is provided as-is without any warranties or guarantees of accuracy. We strongly recommend using this content as a starting point for further research. We disclaim any liability for damages or losses resulting from the use or reliance on this content.
  

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                     